services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway
      - mercadolivre

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - mercadolivre

  mercadolivre:
    build:
      context: ./backend/microservices/mercadolivre
      dockerfile: Dockerfile
    env_file:
      - ./backend/microservices/mercadolivre/.env
    command: npm run start:dev
    volumes:
      - ./backend/microservices/mercadolivre:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest